package com.psl.gems.cardgame.util;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

import com.psl.gems.cardgame.entity.Player;
import com.psl.gems.cardgame.entity.PokerGame;
import com.psl.gems.cardgame.model.Card;

public class HtmlGenerator {

	private PokerGame pokerGame;
	
	public HtmlGenerator(PokerGame pokerGame) {
		this.pokerGame = pokerGame;
	}
	
	public void createHtml() {
		try {
			FileWriter fWriter = new FileWriter("pages/cardgame.html");
			Player p1=pokerGame.getPlayers().get(0);
			Player p2=pokerGame.getPlayers().get(1);
			String p1Name=p1.getName();
			String p2Name=p2.getName();
			Player winner=pokerGame.getWinner();
			ArrayList<Card> p1Cards= p1.getCardsInHand();
			Card p1Highest= p1.getHighestCard();
			ArrayList<Card> p2Cards= p2.getCardsInHand();
			Card p2Highest= p2.getHighestCard();
			fWriter.write("<!DOCTYPE html>\r\n"
					+ "<html>\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "  <meta charset='UTF-8'>\r\n"
					+ "  <title>Poker Game</title>\r\n"
					+ "  <style>\r\n"
					+ "    * {\r\n"
					+ "      margin: 0;\r\n"
					+ "      padding: 0;\r\n"
					+ "      box-sizing: border-box;\r\n"
					+ "    }\r\n"
					+ "    body{\r\n"
					+ "      min-height: 110vh;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .player {\r\n"
					+ "      width: 100%;\r\n"
					+ "      height: 100%;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .flip-card {\r\n"
					+ "\r\n"
					+ "      background-color: transparent;\r\n"
					+ "      margin: 1em;\r\n"
					+ "      width: 10rem;\r\n"
					+ "      height: 15rem;\r\n"
					+ "\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    /* This container is needed to position the front and back side */\r\n"
					+ "    .flip-card-inner {\r\n"
					+ "      position: relative;\r\n"
					+ "      width: 100%;\r\n"
					+ "      height: 100%;\r\n"
					+ "      text-align: center;\r\n"
					+ "      transition: transform 0.8s;\r\n"
					+ "      transform-style: preserve-3d;\r\n"
					+ "\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    /* Position the front and back side */\r\n"
					+ "    .flip-card-front,\r\n"
					+ "    .flip-card-back {\r\n"
					+ "      position: absolute;\r\n"
					+ "      width: 100%;\r\n"
					+ "      height: 100%;\r\n"
					+ "      -webkit-backface-visibility: hidden;\r\n"
					+ "      backface-visibility: hidden;\r\n"
					+ "      border-radius: 0.5em;\r\n"
					+ "\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .flip-card-front:hover {\r\n"
					+ "      background-color: #07ca89;\r\n"
					+ "\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    /* Style the front side (fallback if image is missing) */\r\n"
					+ "    .flip-card-front {\r\n"
					+ "      background-color: dodgerblue;\r\n"
					+ "      color: black;\r\n"
					+ "      background-image: url('../src/resources/images/card-front.jpg');\r\n"
					+ "      background-size: 100%;\r\n"
					+ "      background-repeat: no-repeat;\r\n"
					+ "      background-position: center;\r\n"
					+ "\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    /* Style the back side */\r\n"
					+ "    .flip-card-back {\r\n"
					+ "      background-color: #000000;\r\n"
					+ "      background-image: url('../src/resources/images/spade/ACE.svg');\r\n"
					+ "      background-size: 100%;\r\n"
					+ "      color: white;\r\n"
					+ "      transform: rotateY(180deg);\r\n"
					+ "      background-size: 100%;\r\n"
					+ "      background-repeat: no-repeat;\r\n"
					+ "      background-position: center;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .card-container {\r\n"
					+ "      display: flex;\r\n"
					+ "      align-items: top;\r\n"
					+ "      justify-content: center;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .container {\r\n"
					+ "      display: flex;\r\n"
					+ "      align-items: center;\r\n"
					+ "      justify-content: center;\r\n"
					+ "      padding: 1rem;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .invisible {\r\n"
					+ "      display: none;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .vertical {\r\n"
					+ "      border-left: 4px solid rgb(255, 0, 0);\r\n"
					+ "      height: 80vh;\r\n"
					+ "      position: relative;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    button {\r\n"
					+ "      padding: 0.5em 1em;\r\n"
					+ "      border-radius: 0.5em;\r\n"
					+ "    }\r\n"
					+ "    #winner-btn{\r\n"
					+ "      position: absolute;\r\n"
					+ "      top: 80%;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .win-popup {\r\n"
					+ "      position: absolute;\r\n"
					+ "      height: 90vmax;\r\n"
					+ "      transition: all 6000ms ease-out;\r\n"
					+ "      transform: translateY(-100%);\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .win-animate {\r\n"
					+ "      transform: translateY(100%);\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    #win-popup-container {\r\n"
					+ "      position: absolute;\r\n"
					+ "      top: 0;\r\n"
					+ "      left: 0;\r\n"
					+ "      width: 100%;\r\n"
					+ "      height: 100vh;\r\n"
					+ "      display: flex;\r\n"
					+ "      justify-content: center;\r\n"
					+ "      overflow: hidden;\r\n"
					+ "      z-index: -999;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .popup {\r\n"
					+ "      width: 50%;\r\n"
					+ "      border: 2px solid beige;\r\n"
					+ "      background-color: #CFF4FC;\r\n"
					+ "      margin: 10% auto;\r\n"
					+ "      padding: 2rem;\r\n"
					+ "      text-align: center;\r\n"
					+ "      border-radius: 1rem;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .popup-para {\r\n"
					+ "      margin: 1.75em;\r\n"
					+ "      font-size: 1.25rem;\r\n"
					+ "    }\r\n"
					+ "\r\n"
					+ "    .popup-container {\r\n"
					+ "      z-index: 99;\r\n"
					+ "      position: absolute;\r\n"
					+ "      width: 100%;\r\n"
					+ "      height: 100%;\r\n"
					+ "      display: none;\r\n"
					+ "      top: 0;\r\n"
					+ "      left: 0;\r\n"
					+ "    }\r\n"
					+ "  </style>\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body>\r\n"
					+ "\r\n"
					+ "  <div class='card-container'>\r\n"
					+ "\r\n"
					+ "    <div class='player'>\r\n"
					+ "      <div class='container'>\r\n"
					+ "        <h2>Player 1: "+p1Name+"</h2>\r\n"
					+ "      </div>\r\n"
					+ "      <div class='card-container'>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP1(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p1-1'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP1(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p1-2'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP1(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p1-3'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "\r\n"
					+ "      </div>\r\n"
					+ "      <div class='container'>\r\n"
					+ "        <button id='p1-highest-btn' disabled onclick='showHighestP1()'>Show Highest Card</button>\r\n"
					+ "      </div>\r\n"
					+ "      <div class='card-container invisible' id='p1-highest-card'>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' id='card-p1-H'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "      </div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "    </div>\r\n"
					+ "\r\n"
					+ "    <div class='vertical'></div>\r\n"
					+ "\r\n"
					+ "    <div class='player'>\r\n"
					+ "      <div class='container'>\r\n"
					+ "        <h2>Player 2: "+p2Name+"</h2>\r\n"
					+ "      </div>\r\n"
					+ "      <div class='card-container'>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP2(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p2-1'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP2(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p2-2'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' onclick='flipP2(this)'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back' id='card-p2-3'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "\r\n"
					+ "      </div>\r\n"
					+ "      <div class='container'>\r\n"
					+ "        <button id='p2-highest-btn' disabled onclick='showHighestP2()'>Show Highest Card</button>\r\n"
					+ "      </div>\r\n"
					+ "\r\n"
					+ "      <div class='card-container invisible' id='p2-highest-card'>\r\n"
					+ "        <div class='flip-card'>\r\n"
					+ "          <div class='flip-card-inner'>\r\n"
					+ "            <div class='flip-card-front' id='card-p2-H'>\r\n"
					+ "            </div>\r\n"
					+ "            <div class='flip-card-back'>\r\n"
					+ "            </div>\r\n"
					+ "          </div>\r\n"
					+ "        </div>\r\n"
					+ "      </div>\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "  <div class='container'>\r\n"
					+ "    <button id='winner-btn' disabled onclick='showWinner()'>Decide Winner</button>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "  <div id='win-popup-container'>\r\n"
					+ "    <img class='win-popup' src='../src/resources/images/congrats.svg' alt='' srcset=''>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "  <div class='popup-container'>\r\n"
					+ "\r\n"
					+ "    <div class='popup'>\r\n"
					+ "      <h2>Congratulations "+winner.getName()+" !!! You have won the Game </h2>\r\n"
					+ "      <p class='popup-para'>Congratulations "+winner.getName()+" on winning the Poker Game with score of "+winner.getHighestCard().getValue()+". Hope you enjoyed and had a great time\r\n"
					+ "        playing.</p>\r\n"
					+ "    </div>\r\n"
					+ "  </div>\r\n"
					+ "\r\n"
					+ "</body>\r\n"
					+ "<script>\r\n"
					+ "  var p1Counter = 0;\r\n"
					+ "  let p1HighestBtn = document.getElementById('p1-highest-btn');\r\n"
					+ "  let p1HighestCard = document.getElementById('p1-highest-card');\r\n"
					+ "\r\n"
					+ "  var p2Counter = 0;\r\n"
					+ "  let p2HighestBtn = document.getElementById('p2-highest-btn');\r\n"
					+ "  let p2HighestCard = document.getElementById('p2-highest-card');\r\n"
					+ "\r\n"
					+ "  var isGameOver = false;\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "  function flipP1(e) {\r\n"
					+ "    e.parentElement.style.transform = 'rotateY(180deg)';\r\n"
					+ "    p1Counter++;\r\n"
					+ "    if (p1Counter === 3)\r\n"
					+ "      p1HighestBtn.disabled = false;\r\n"
					+ "  };\r\n"
					+ "\r\n"
					+ "  function flipP2(e) {\r\n"
					+ "    e.parentElement.style.transform = 'rotateY(180deg)';\r\n"
					+ "    p2Counter++;\r\n"
					+ "    if (p2Counter === 3)\r\n"
					+ "      p2HighestBtn.disabled = false;\r\n"
					+ "  };\r\n"
					+ "\r\n"
					+ "  function showHighestP1() {\r\n"
					+ "    p1HighestCard.classList.remove('invisible');\r\n"
					+ "    if (isGameOver)\r\n"
					+ "      document.getElementById('winner-btn').disabled = false;\r\n"
					+ "    else isGameOver = true;\r\n"
					+ "\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "  function showHighestP2() {\r\n"
					+ "    p2HighestCard.classList.remove('invisible');\r\n"
					+ "    if (isGameOver)\r\n"
					+ "      document.getElementById('winner-btn').disabled = false;\r\n"
					+ "    else isGameOver = true;\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "  function showWinner() {\r\n"
					+ "    let popup=document.querySelector('.popup-container');\r\n"
					+ "    popup.style.display = 'block';\r\n"
					+ "    document.querySelector('.win-popup').classList.add('win-animate');\r\n"
					+ "    document.querySelector('.win-popup-container').style.zIndex='999';\r\n"
					+ "    popup.style.zIndex='999';\r\n"
					+ "  }\r\n"
					+ "\r\n"
					+ "  function setimages() {\r\n"
					+ "    document.getElementById('card-p1-1').style.backgroundImage = `url('../src/resources/images/"+p1Cards.get(0).getSuit()+"/"+p1Cards.get(0).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p1-2').style.backgroundImage = `url('../src/resources/images/"+p1Cards.get(1).getSuit()+"/"+p1Cards.get(1).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p1-3').style.backgroundImage = `url('../src/resources/images/"+p1Cards.get(2).getSuit()+"/"+p1Cards.get(2).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p1-H').style.backgroundImage = `url('../src/resources/images/"+p1Highest.getSuit()+"/"+p1Highest.getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p2-1').style.backgroundImage = `url('../src/resources/images/"+p2Cards.get(0).getSuit()+"/"+p2Cards.get(0).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p2-2').style.backgroundImage = `url('../src/resources/images/"+p2Cards.get(1).getSuit()+"/"+p2Cards.get(1).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p2-3').style.backgroundImage = `url('../src/resources/images/"+p2Cards.get(2).getSuit()+"/"+p2Cards.get(2).getRank()+".svg')`;\r\n"
					+ "    document.getElementById('card-p2-H').style.backgroundImage = `url('../src/resources/images/"+p2Highest.getSuit()+"/"+p2Highest.getRank()+".svg')`;\r\n"
					+ "  }\r\n"
					+ "  setimages();\r\n"
					+ "</script>\r\n"
					+ "\r\n"
					+ "</html>");
			fWriter.close();
		} catch (IOException e) {
			
			e.printStackTrace();
		}
	}

	public PokerGame getPokerGame() {
		return pokerGame;
	}


	

}
